### ISSUE TITLE
Connect gets EPERM

### ISSUE THREAD

**Issue by DaKnOb** [gutworth/httpswatch#27]
The script fails to access a few hosts by reporting ```EPERM``` on ```connect()``` while they are accessible, although usually have HTTPS errors like ```NET::ERR_CERT_AUTHORITY_INVALID```, ```403:FORBIDDEN```, ```ERR_SSL_PROTOCOL_ERROR```, ```HTTP-META-REDIRECT```, ```ERR_CERT_COMMON_NAME_INVALID```. There are also sites that cause this problem that are perfectly fine and accessible through a web browser (even Firefox). 

For the hosted copy that has these errors live, see https://httpswatch.daknob.net/

**Comment by DaKnOb** [comment]
The certificate-related issues can be accepted as possible causes since they are probably caused because you supply the ```moz-certs.pem``` in the library directly. The ```HTTP``` related ones though do not really make much sense.. 
If only there was a way to better identify the error and print that instead of a simple ```EPERM``` on ```connect()```.

**Comment by gutworth** [comment]
This should be fixed now.

**Comment by DaKnOb** [comment]
Okay, now sites do not show up as ```EPERM``` when failing. The problem still remains as described in issue #16 though.
